[phases.setup]
nixPkgs = ['nodejs_18']

[phases.install]
cmds = [
  'rm -rf node_modules',
  'npm install --include=optional'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'npm start'
