// Game Constants - Centralized configuration for better maintainability

export const GAME_CONSTANTS = {
  // Grid dimensions
  GRID_ROWS: 3,
  GRID_COLS: 4,

  // Item scaling
  ITEM_SCALE_NORMAL: 0.075,
  ITEM_SCALE_DRAG: 0.090,
  ITEM_SCALE_PICKUP: 0.075 * 1.5,

  // Animation durations (ms)
  ANIMATION_POP_IN: 300,
  ANIMATION_ELIMINATION: 400,
  ANIMATION_BOUNCE: 150,
  ANIMATION_SCALE: 100,
  ANIMATION_FADE: 700,

  // Timing delays (ms)
  DELAY_ELIMINATION: 300,
  DELAY_REFILL: 1000,
  DELAY_COMBO_RESET: 2000,
  DELAY_CHECK_ELIMINATION: 100,
  DELAY_CHECK_DEADLOCK: 500,

  // Combo system
  COMBO_RESET_DELAY: 2000,
  COMBO_BASE_POINTS: 100,

  // UI depths
  DEPTH_BACKGROUND: -200,
  DEPTH_BACKGROUND_OVERLAY: -50,
  DEPTH_GRID: 50,
  DEPTH_ITEMS: 100,
  DEPTH_UI: 2000,
  DEPTH_UI_TEXT: 2100,
  DEPTH_OVERLAY: 9999,
  DEPTH_NOTIFICATION: 10000,
  DEPTH_NOTIFICATION_TEXT: 10001,

  // Position offsets for 3-position slots
  POSITION_OFFSETS: [
    { x: -0.25, y: 0.15 },  // Left position
    { x: 0, y: 0.15 },      // Middle position
    { x: 0.25, y: 0.15 }    // Right position
  ],

  // Detection boundaries for position selection
  POSITION_DETECTION_BOUNDARY: 0.2,

  // Tween ease types
  EASE_BACK_OUT: 'Back.easeOut',
  EASE_BOUNCE_OUT: 'Bounce.easeOut',
  EASE_POWER2_OUT: 'Power2.easeOut',
  EASE_SINE_IN_OUT: 'Sine.easeInOut',
  EASE_ELASTIC_OUT: 'Elastic.easeOut',

  // Audio volumes
  VOLUME_SFX_NORMAL: 0.5,
  VOLUME_SFX_LOW: 0.3,
  VOLUME_SFX_HIGH: 1.2,
  VOLUME_MUSIC: 0.3,

  // Shuffle warning duration
  SHUFFLE_WARNING_DURATION: 300,

  // Help message duration
  HELP_MESSAGE_DURATION: 2000,

  // Notification delays
  OPPONENT_LEFT_DELAY: 2000,

  // Periodic check intervals
  PERIODIC_MATCH_CHECK_INTERVAL: 3000,
  NO_MOVES_CHECK_INTERVAL: 5000,

  // Obstacle spawn intervals
  OBSTACLE_FIRST_SPAWN_MIN: 8,
  OBSTACLE_FIRST_SPAWN_MAX: 12,
  OBSTACLE_SPAWN_INTERVAL_MIN: 15,
  OBSTACLE_SPAWN_INTERVAL_MAX: 25,

  // Tom event intervals
  TOM_EVENT_FIRST_DELAY_MIN: 20,
  TOM_EVENT_FIRST_DELAY_MAX: 30,
  TOM_EVENT_INTERVAL_MIN: 30,
  TOM_EVENT_INTERVAL_MAX: 50,

  // Fill percentages
  GRID_FILL_MIN: 60,
  GRID_FILL_MAX: 70,
  DEADLOCK_EMPTY_THRESHOLD: 0.3,
  DEADLOCK_FULL_THRESHOLD: 0.2,

  // Target spawn chances
  TARGET_SPAWN_START: 35,
  TARGET_SPAWN_REFILL: 40,
  OBSTACLE_SPAWN_CHANCE: 20,

  // UI spacing
  UI_TOP_SPACE: 160,
  UI_BOTTOM_SPACE: 80,
  UI_SIDE_SPACE: 120,

  // Slot spacing
  SLOT_SPACING: 20,

  // Tom cat animation
  TOM_BREATHING_Y: 5,
  TOM_BLINK_CHANCE: 0.3,
  TOM_HEAD_TURN_CHANCE: 0.5,
  TOM_HEAD_TURN_DISTANCE: 30,

  // Drag ring properties
  DRAG_RING_SCALE: 1.3,
  DRAG_RING_ALPHA: 0.4,
  DRAG_RING_DURATION: 800,

  // Highlight properties
  HIGHLIGHT_PULSE_DURATION: 500,
  HIGHLIGHT_AVAILABLE_ALPHA: 0.8,
  HIGHLIGHT_FULL_RED: 0.9,

  // Combo display thresholds
  COMBO_MEGA_THRESHOLD: 5,
  COMBO_X3_THRESHOLD: 3,
  COMBO_X2_THRESHOLD: 2,

  // Score display bounce
  SCORE_BOUNCE_SCALE: 1.2,

  // Shuffle animation
  SHUFFLE_CENTER_X: 0,
  SHUFFLE_CENTER_Y: 0,
  SHUFFLE_SCALE_ZERO: 0,
  SHUFFLE_DURATION: 500,
  SHUFFLE_STAGGER_DELAY: 10,
  SHUFFLE_WAIT_DURATION: 800,

  // Obstacle fall properties
  OBSTACLE_FALL_START_Y: -100,
  OBSTACLE_FALL_DURATION: 600,
  OBSTACLE_FALL_STAGGER: 300,

  // Jerry escape properties
  JERRY_ESCAPE_DISTANCE: 180,
  JERRY_ESCAPE_UPWARD: 40,
  JERRY_ESCAPE_ROTATION: 0.1,
  JERRY_ESCAPE_DURATION: 400,

  // Dust trail properties
  DUST_TRAIL_COUNT: 5,
  DUST_TRAIL_INTERVAL: 500,
  DUST_TRAIL_OFFSET_Y: 20,

  // Screen shake properties
  SCREEN_SHAKE_DURATION: 2000,
  SCREEN_SHAKE_INTENSITY: 0.01,
  SCREEN_SHAKE_ITEM_VIBRATION: 5,
  SCREEN_SHAKE_VIBRATION_DURATION: 50,
  SCREEN_SHAKE_VIBRATION_REPEATS: 40,

  // Help items properties
  HELP_ITEM_COUNT: 3,
  HELP_ITEM_FALL_DURATION: 600,
  HELP_ITEM_FLASH_COUNT: 3,
  HELP_ITEM_FLASH_DURATION: 200,

  // Notification properties
  NOTIFICATION_SCALE_IN_DURATION: 400,
  NOTIFICATION_FADE_IN_DURATION: 300,
  NOTIFICATION_STAY_DURATION: 2000,
  NOTIFICATION_FADE_OUT_DURATION: 500,

  // Sparkle effects
  SPARKLE_COUNT: 5,
  SPARKLE_RISE_DISTANCE: 30,
  SPARKLE_RISE_DURATION: 600,
  SPARKLE_STAGGER_DELAY: 100,

  // Halo effect properties
  HALO_RING_SCALE: 2.5,
  HALO_RING_DURATION: 600,
  HALO_RING_ROTATION: Math.PI,

  // Score float properties
  SCORE_FLOAT_UP_DISTANCE: 70,
  SCORE_FLOAT_DURATION: 300,
  SCORE_FLOAT_FADE_START: 90,
  SCORE_FLOAT_FADE_DURATION: 700,

  // Timer warning colors
  TIMER_WARNING_10SEC: '#FF0000',
  TIMER_WARNING_30SEC: '#FF6347',

  // Opponent UI properties
  OPPONENT_ICON_SCALE: 0.042,
  OPPONENT_UPDATE_ANIMATION_DURATION: 150,

  // Mobile tutorial delay
  MOBILE_TUTORIAL_DELAY: 500,

  // Initial stats sync delay
  INITIAL_STATS_SYNC_DELAY: 500,

  // Missed match scan delay
  MISSED_MATCH_DELAY: 200,

  // Game end sound delay
  GAME_END_SOUND_DELAY: 150,

  // Loading complete delay
  LOADING_COMPLETE_DELAY: 500,
  LOADING_TRANSITION_DELAY: 1500,

  // Jerry animation delays
  JERRY_POP_DELAY: 150,
  JERRY_STAY_DELAY: 300,
  JERRY_SMOKE_DELAY: 600,

  // Tom event delays
  TOM_SLIDE_DELAY: 800,
  TOM_LAUGH_DELAY: 500,
  TOM_CRASH_DELAY: 1500,
  TOM_FALL_DELAY: 800,
  TOM_OBSTACLE_DROP_DELAY: 300,
  TOM_SHAKE_DELAY: 1000,
  TOM_DISAPPEAR_DELAY: 2500,

  // Dust cloud expansion
  DUST_CLOUD_SCALE: 0.08,
  DUST_CLOUD_ALPHA: 0.8,
  DUST_CLOUD_EXPAND_SCALE: 0.12,
  DUST_CLOUD_EXPAND_DURATION: 600,
  DUST_CLOUD_MOVE_DISTANCE: 200,

  // Jerry pop effect
  JERRY_POP_SCALE: 0.08,
  JERRY_POP_DURATION: 150,
  JERRY_POP_EASE: 'Back.easeOut.config(1.7)',

  // Jerry escape effect
  JERRY_ESCAPE_SCALE_X: 0.05,
  JERRY_ESCAPE_SCALE_Y: 0.05,
  JERRY_ESCAPE_EASE: 'Quad.easeOut',

  // Rainbow halo properties
  HALO_OUTER_LINE_STYLE: 8,
  HALO_MIDDLE_LINE_STYLE: 6,
  HALO_INNER_LINE_STYLE: 4,
  HALO_OUTER_COLOR: 0xFF69B4,
  HALO_MIDDLE_COLOR: 0xDA70D6,
  HALO_INNER_COLOR: 0xFFFFFF,
  HALO_OUTER_ALPHA: 0.7,
  HALO_MIDDLE_ALPHA: 0.8,
  HALO_INNER_ALPHA: 0.9,
  HALO_OUTER_RADIUS: 25,
  HALO_MIDDLE_RADIUS: 18,
  HALO_INNER_RADIUS: 12,

  // Cute effects properties
  CUTE_EFFECTS: ['✨', '💖', '🌟', '💫', '🎀', '🌈', '💕', '⭐'],
  CUTE_EFFECT_COUNT: 10,
  CUTE_EFFECT_ANGLE_STEP: Math.PI * 2 / 10,
  CUTE_EFFECT_DISTANCE_MIN: 40,
  CUTE_EFFECT_DISTANCE_MAX: 80,
  CUTE_EFFECT_ROTATION: Phaser.Math.Between(-Math.PI, Math.PI),
  CUTE_EFFECT_SCALE_MIN: 0.1,
  CUTE_EFFECT_SCALE_MAX: 0.3,
  CUTE_EFFECT_DURATION_MIN: 500,
  CUTE_EFFECT_DURATION_MAX: 800,
  CUTE_EFFECT_STAGGER: 30,

  // Combo text properties
  COMBO_TEXT_MEGA: '🔥 MEGA COMBO x',
  COMBO_TEXT_X3: '⚡ COMBO x',
  COMBO_TEXT_X2: '✨ COMBO x',
  COMBO_TEXT_Y_OFFSET: 80,
  COMBO_TEXT_Y_FINAL: 120,
  COMBO_TEXT_SCALE: 1.3,
  COMBO_TEXT_DURATION: 1000,

  // Score text properties
  SCORE_TEXT_PREFIX: '+',
  SCORE_TEXT_SUFFIX: ' 💎',
  SCORE_TEXT_X_OFFSET: 35,
  SCORE_TEXT_Y_OFFSET: 25,
  SCORE_TEXT_SCALE: 1.2,

  // Obstacle impact properties
  IMPACT_RING_COUNT: 3,
  IMPACT_RING_DURATION_BASE: 400,
  IMPACT_RING_SCALE_BASE: 3,
  IMPACT_RING_STAGGER: 100,
  IMPACT_STAR_COUNT: 8,
  IMPACT_STAR_DISTANCE: 50,

  // Shuffle warning properties
  SHUFFLE_WARNING_TEXT: '🔄 NO MOVES LEFT!\nSHUFFLING...',
  SHUFFLE_WARNING_FONT_SIZE: '36px',
  SHUFFLE_WARNING_FADE_DURATION: 300,

  // Help message properties
  HELP_MESSAGE_FONT_SIZE: '28px',
  HELP_MESSAGE_SCALE: 1.2,
  HELP_MESSAGE_FADE_IN_DURATION: 300,
  HELP_MESSAGE_FADE_OUT_DURATION: 300,

  // Opponent left notification properties
  OPPONENT_LEFT_TEXT: '👋 OPPONENT DISCONNECTED',
  OPPONENT_LEFT_SUBTEXT: 'You win by default!',
  OPPONENT_LEFT_PANEL_WIDTH: 400,
  OPPONENT_LEFT_PANEL_HEIGHT: 150,
  OPPONENT_LEFT_OVERLAY_ALPHA: 0.5,
  OPPONENT_LEFT_PANEL_SCALE: 0,
  OPPONENT_LEFT_TEXT_SCALE: 0,
  OPPONENT_LEFT_FADE_DURATION: 300,
  OPPONENT_LEFT_SCALE_DURATION: 400,
  OPPONENT_LEFT_STAY_DURATION: 2000,

  // Scene label properties
  SCENE_LABEL_OFFSET_X: -20,
  SCENE_LABEL_OFFSET_Y: -20,
  SCENE_LABEL_FADE_DURATION: 1000,
  SCENE_LABEL_ALPHA: 0.8,

  // Scene labels mapping
  SCENE_LABELS: {
    'tom_jerry_kitchen_background': '🍽️ KITCHEN CHAOS',
    'tom_jerry_living_room_background': '🛋️ LIVING ROOM MAYHEM',
    'tom_jerry_garden_background': '🌻 GARDEN ADVENTURE',
    'tom_jerry_basement_background': '🕳️ BASEMENT MYSTERY'
  },

  // Jerry animation properties
  JERRY_ANIMATION_DELAY_MIN: 3000,
  JERRY_ANIMATION_DELAY_MAX: 6000,
  JERRY_ANIMATION_Y_MIN: 0.3,
  JERRY_ANIMATION_Y_MAX: 0.7,
  JERRY_ANIMATION_X_RANDOM: Phaser.Math.Between(50, 100),
  JERRY_ANIMATION_SCALE: 0.08,
  JERRY_ANIMATION_POP_SCALE: 0.08,
  JERRY_ANIMATION_POP_DURATION: 150,
  JERRY_ANIMATION_STAY_DURATION: 300,
  JERRY_ANIMATION_ESCAPE_X: 250,
  JERRY_ANIMATION_ESCAPE_Y: 50,
  JERRY_ANIMATION_ESCAPE_DURATION: 400,

  // Dust trail properties
  DUST_TRAIL_SCALE: 0.08,
  DUST_TRAIL_ALPHA: 0.6,
  DUST_TRAIL_FADE_DURATION: 800,

  // Mobile indicator properties
  MOBILE_INDICATOR_TEXT: '📱 MOBILE MODE',
  MOBILE_INDICATOR_Y: 30,
  MOBILE_INDICATOR_FONT_SIZE: '18px',
  MOBILE_INDICATOR_BLINK_DURATION: 1000,

  // Title animation properties
  TITLE_FLOAT_DISTANCE: 8,
  TITLE_FLOAT_DURATION: 1500,
  TITLE_SCALE_MIN: 0.95,
  TITLE_SCALE_MAX: 1.05,
  TITLE_SCALE_DURATION: 1800,

  // Tagline animation properties
  TAGLINE_SCALE_MIN: 0.95,
  TAGLINE_SCALE_MAX: 1.05,
  TAGLINE_SCALE_DURATION: 1800,

  // Button properties
  BUTTON_HOVER_SCALE: 0.45,
  BUTTON_NORMAL_SCALE: 0.4,
  BUTTON_CLICK_SCALE: 0.35,
  BUTTON_TEXT_SCALE_NORMAL: 1,
  BUTTON_TEXT_SCALE_HOVER: 1.1,
  BUTTON_TEXT_SCALE_CLICK: 0.9,
  BUTTON_ANIMATION_DURATION: 100,

  // Hint text properties
  HINT_BLINK_DURATION: 800,
  HINT_ALPHA_MIN: 0.5,
  HINT_ALPHA_MAX: 1,

  // Loading progress properties
  LOADING_TITLE_Y: 0.3,
  LOADING_PROGRESS_Y: 0.55,
  LOADING_TIPS_Y: 0.75,
  LOADING_JERRY_Y_OFFSET: 25,
  LOADING_JERRY_BOUNCE: 3,
  LOADING_JERRY_SCALE_MIN: 0.08,
  LOADING_JERRY_SCALE_MAX: 0.11,
  LOADING_JERRY_EXCITE_THRESHOLD: 0.9,
  LOADING_JERRY_EXCITE_TINT: 0xFFFFAA,
  LOADING_JERRY_CELEBRATION_SCALE: 0.15,
  LOADING_JERRY_CELEBRATION_ROTATION: 360,
  LOADING_JERRY_JUMP_Y: 15,
  LOADING_JERRY_FALL_DURATION: 400,

  // Loading tips
  LOADING_TIPS: [
    "🧀 Match 3 cheese to score points!",
    "🏃 Help Jerry escape from Tom!",
    "⭐ Create special combos for bonus points!",
    "🎯 Complete objectives to win!",
    "🔥 Use power-ups strategically!"
  ],
  LOADING_TIP_SWITCH_DELAY: 2000,

  // Background decorative dots
  BG_DOT_COUNT: 20,
  BG_DOT_SIZE_MIN: 3,
  BG_DOT_SIZE_MAX: 8,
  BG_DOT_ALPHA: 0.1,

  // Shelf properties
  SHELF_TRANSPARENCY: 0.3,
  SHELF_FRAME_WIDTH: 12,
  SHELF_SLOT_TRANSPARENCY: 0.4,
  SHELF_DIVIDER_TRANSPARENCY: 0.5,
  SHELF_METAL_TRANSPARENCY: 0.4,
  SHELF_CORNER_SIZE: 20,

  // Shelf colors
  SHELF_WOOD_LIGHT: 0xDEB887,
  SHELF_WOOD_MEDIUM: 0xCD853F,
  SHELF_WOOD_DARK: 0x8B4513,
  SHELF_WOOD_SHADOW: 0x654321,
  SHELF_WOOD_HIGHLIGHT: 0xF5DEB3,
  SHELF_METAL_COLOR: 0x708090,

  // Shelf metallic effects
  SHELF_METALLIC_HIGHLIGHT: 0xF0F0F0,
  SHELF_METALLIC_SHADOW: 0xD0D0D0,
  SHELF_METALLIC_HIGHLIGHT_TRANSPARENCY: 0.3,
  SHELF_METALLIC_SHADOW_TRANSPARENCY: 0.2,
  SHELF_METALLIC_CIRCLE_SIZE: 3,

  // Target display properties
  TARGET_BG_GRADIENT_START: 0xFFFACD,
  TARGET_BG_GRADIENT_END: 0xF5DEB3,
  TARGET_BG_ALPHA: 0.95,
  TARGET_BG_RADIUS: 20,
  TARGET_BORDER_WIDTH: 4,
  TARGET_ICON_SCALE: 0.050,
  TARGET_ICON_BLINK_DURATION: 1000,
  TARGET_ICON_BLINK_SCALE: 1.1,
  TARGET_TEXT_OFFSET_Y: 115,
  TARGET_COMPLETED_CHECKMARK: '✅',
  TARGET_COMPLETED_COLOR: '#32CD32',
  TARGET_COMPLETED_ANIMATION_SCALE: 1.2,
  TARGET_COMPLETED_ANIMATION_DURATION: 200,
  TARGET_COMPLETED_ANIMATION_REPEATS: 2,

  // Move counter properties
  MOVE_COUNTER_BG_GRADIENT_START: 0x87CEEB,
  MOVE_COUNTER_BG_GRADIENT_END: 0xADD8E6,
  MOVE_COUNTER_BG_ALPHA: 0.95,
  MOVE_COUNTER_BG_RADIUS: 15,
  MOVE_COUNTER_TEXT_Y: 50,
  MOVE_COUNTER_WARNING_COLOR: '#FF6347',
  MOVE_COUNTER_WARNING_TEXT: '⚠️ Moves: ',

  // Endless mode properties
  ENDLESS_MODE_ICON: '♾️',
  ENDLESS_MODE_BG_GRADIENT_START: 0x9370DB,
  ENDLESS_MODE_BG_GRADIENT_END: 0xBA55D3,

  // Time attack mode properties
  TIME_ATTACK_MODE_ICON: '⏱️',
  TIME_ATTACK_MODE_BG_GRADIENT_START: 0xFF6347,
  TIME_ATTACK_MODE_BG_GRADIENT_END: 0xFF7F50,
  TIME_ATTACK_INITIAL_TIME: 120,

  // Score display properties
  SCORE_BG_GRADIENT_START: 0x9370DB,
  SCORE_BG_GRADIENT_END: 0xBA55D3,
  SCORE_TEXT_PREFIX: '🏆 Score: ',
  SCORE_UPDATE_ANIMATION_SCALE: 1.2,
  SCORE_UPDATE_ANIMATION_DURATION: 150,

  // Pause button properties
  PAUSE_BUTTON_BG_GRADIENT_START: 0xFF8C00,
  PAUSE_BUTTON_BG_GRADIENT_END: 0xFFA500,
  PAUSE_BUTTON_BG_ALPHA: 0.95,
  PAUSE_BUTTON_WIDTH: 100,
  PAUSE_BUTTON_HEIGHT: 45,
  PAUSE_BUTTON_RADIUS: 22,
  PAUSE_BUTTON_TEXT: '⏸️ PAUSE',
  PAUSE_BUTTON_TEXT_Y: 122,
  PAUSE_BUTTON_HOVER_TINT: 0xFFFF88,
  PAUSE_BUTTON_CLICK_TINT: 0xCCCC44,

  // Opponent panel properties
  OPPONENT_BG_GRADIENT_START: 0xFF6B6B,
  OPPONENT_BG_GRADIENT_END: 0xFF8E8E,
  OPPONENT_BG_ALPHA: 0.95,
  OPPONENT_BG_RADIUS: 15,
  OPPONENT_TITLE: '👤 OPPONENT',
  OPPONENT_TITLE_Y: 103,
  OPPONENT_ICON_Y: 138,
  OPPONENT_TEXT_Y_OFFSET: 26,
  OPPONENT_ITEM_SPACING: 0.06,

  // Background scene properties
  BG_SCENE_SCALE_X: 1536,
  BG_SCENE_SCALE_Y: 1024,
  BG_SCENE_ALPHA: 0.8,
  BG_SCENE_DEPTH: -100,

  // Background colors by scene
  BG_COLOR_KITCHEN: 0x8B7355,
  BG_COLOR_LIVING_ROOM: 0x6B8E8E,
  BG_COLOR_GARDEN: 0x7B8B6B,
  BG_COLOR_BASEMENT: 0x696969,
  BG_COLOR_DEFAULT: 0x808080,

  // Border properties
  BORDER_THICKNESS: 6,
  BORDER_INNER_THICKNESS: 3,
  BORDER_OUTER_COLOR: 0x000000,
  BORDER_INNER_COLOR: 0xFFFFFF,
  BORDER_OUTER_ALPHA: 0.3,
  BORDER_INNER_ALPHA: 0.4,
  BORDER_RADIUS: 15,

  // Watching cat properties
  WATCHING_CAT_SCALE: 0.18,
  WATCHING_CAT_DEPTH: 85,
  WATCHING_CAT_ORIGIN_X: 0.5,
  WATCHING_CAT_ORIGIN_Y: 1.0,
  WATCHING_CAT_BREATH_DURATION: 2000,
  WATCHING_CAT_BLINK_DELAY: 3000,
  WATCHING_CAT_BLINK_CHANCE: 0.7,
  WATCHING_CAT_BLINK_SCALE: 0.16,
  WATCHING_CAT_BLINK_DURATION: 100,
  WATCHING_CAT_TURN_DELAY: 5000,
  WATCHING_CAT_TURN_CHANCE: 0.5,
  WATCHING_CAT_TURN_DISTANCE: 30,
  WATCHING_CAT_TURN_DURATION: 500,
  WATCHING_CAT_HOLD_DURATION: 1000,

  // Item pickup animation
  ITEM_PICKUP_SCALE: 1.5,
  ITEM_PICKUP_DURATION: 150,
  ITEM_PICKUP_YOYO: true,

  // Item drag tint
  ITEM_DRAG_TINT: 0xFFB6C1,

  // Slot highlight properties
  SLOT_HIGHLIGHT_LINE_WIDTH: 4,
  SLOT_HIGHLIGHT_AVAILABLE_COLOR: 0x00FF00,
  SLOT_HIGHLIGHT_FULL_COLOR: 0xFF0000,
  SLOT_HIGHLIGHT_STROKE_WIDTH: 8,
  SLOT_HIGHLIGHT_DEPTH: 45,

  // Item elimination animation
  ITEM_ELIMINATION_SCALE: 1.5,
  ITEM_ELIMINATION_DURATION: 150,
  ITEM_ELIMINATION_ROTATION: Math.PI * 2,
  ITEM_ELIMINATION_FADE_DURATION: 400,
  ITEM_ELIMINATION_STAGGER: 50,

  // Obstacle unlock animation
  OBSTACLE_UNLOCK_SCALE: 0.09,
  OBSTACLE_UNLOCK_DURATION: 200,

  // Shuffle animation properties
  SHUFFLE_ANIMATION_SCALE: 0,
  SHUFFLE_ANIMATION_ROTATION: Math.PI * 2,
  SHUFFLE_ANIMATION_ALPHA: 0.5,
  SHUFFLE_ANIMATION_EASE: 'Back.easeIn',

  // Texture filtering
  TEXTURE_FILTER_LINEAR: 1,
  TEXTURE_SCALE_MODE_LINEAR: 1,

  // Blend modes
  BLEND_MODE_NORMAL: Phaser.BlendModes.NORMAL,

  // Alpha values
  ALPHA_OPAQUE: 1.0,
  ALPHA_TRANSPARENT: 0,
  ALPHA_HALF: 0.5,

  // Scale values
  SCALE_ZERO: 0,
  SCALE_NORMAL: 1,
  SCALE_DOUBLE: 2,

  // Math constants
  PI: Math.PI,
  PI_DOUBLE: Math.PI * 2,
  PI_HALF: Math.PI / 2,

  // Random ranges
  RANDOM_DELAY_MIN: 0,
  RANDOM_DELAY_MAX: 200,
  RANDOM_STAGGER_MIN: 0,
  RANDOM_STAGGER_MAX: 300,
  RANDOM_ROTATION_MIN: -Math.PI,
  RANDOM_ROTATION_MAX: Math.PI,
  RANDOM_SCALE_MIN: 0.1,
  RANDOM_SCALE_MAX: 0.3,
  RANDOM_DURATION_MIN: 500,
  RANDOM_DURATION_MAX: 800,
  RANDOM_DISTANCE_MIN: 40,
  RANDOM_DISTANCE_MAX: 80,
  RANDOM_ANGLE_OFFSET: 0.5,

  // Array indices
  INDEX_FIRST: 0,
  INDEX_SECOND: 1,
  INDEX_THIRD: 2,

  // Time conversions
  SECONDS_TO_MS: 1000,
  MINUTES_TO_SECONDS: 60,

  // Percentage conversions
  PERCENT_TO_DECIMAL: 100,

  // Grid calculations
  GRID_POSITIONS_PER_SLOT: 3,
  GRID_TOTAL_MULTIPLIER: 3,

  // UI layout calculations
  UI_GRID_START_OFFSET: 0.15,
  UI_GRID_TARGET_OFFSET: 0.08,
  UI_GRID_TARGET_SPACING: 0.07,
  UI_GRID_MOVE_X: 0.8,
  UI_GRID_SCORE_X: 0.475,
  UI_GRID_OPPONENT_X: 0.815,
  UI_GRID_OPPONENT_BASE_X: 0.735,

  // Font sizes
  FONT_SIZE_TITLE: '48px',
  FONT_SIZE_PROGRESS: '24px',
  FONT_SIZE_TIPS: '20px',
  FONT_SIZE_TARGET_TITLE: '20px',
  FONT_SIZE_TARGET_COUNT: '16px',
  FONT_SIZE_MOVE_COUNTER: '18px',
  FONT_SIZE_SCORE: '18px',
  FONT_SIZE_BUTTON: '16px',
  FONT_SIZE_OPPONENT_TITLE: '14px',
  FONT_SIZE_OPPONENT_COUNT: '12px',
  FONT_SIZE_HINT: '16px',
  FONT_SIZE_TAGLINE: '28px',
  FONT_SIZE_START_BUTTON: '32px',
  FONT_SIZE_MOBILE_INDICATOR: '18px',
  FONT_SIZE_SCENE_LABEL: '14px',
  FONT_SIZE_SHUFFLE_WARNING: '36px',
  FONT_SIZE_HELP_MESSAGE: '28px',
  FONT_SIZE_NOTIFICATION: '24px',
  FONT_SIZE_NOTIFICATION_SUB: '18px',
  FONT_SIZE_COMBO_MEGA: '28px',
  FONT_SIZE_COMBO_NORMAL: '24px',
  FONT_SIZE_COMBO_SMALL: '22px',
  FONT_SIZE_SCORE_FLOAT: '24px',
  FONT_SIZE_SPARKLE: '20px',
  FONT_SIZE_CUTE_EFFECT_MIN: '14px',
  FONT_SIZE_CUTE_EFFECT_MAX: '22px',

  // Font families
  FONT_FAMILY_GAME: 'window.getGameFont()',
  FONT_FAMILY_DEFAULT: 'Arial, sans-serif',

  // Colors
  COLOR_WHITE: '#FFFFFF',
  COLOR_BLACK: '#000000',
  COLOR_RED: '#FF0000',
  COLOR_GREEN: '#00FF00',
  COLOR_BLUE: '#0000FF',
  COLOR_YELLOW: '#FFFF00',
  COLOR_PURPLE: '#800080',
  COLOR_ORANGE: '#FFA500',
  COLOR_PINK: '#FFC0CB',
  COLOR_CYAN: '#00FFFF',
  COLOR_MAGENTA: '#FF00FF',
  COLOR_GRAY: '#808080',
  COLOR_BROWN: '#8B4513',
  COLOR_GOLD: '#FFD700',
  COLOR_SILVER: '#C0C0C0',

  // Stroke colors
  STROKE_BLACK: '#000000',
  STROKE_WHITE: '#FFFFFF',
  STROKE_RED: '#FF0000',
  STROKE_BLUE: '#0000FF',
  STROKE_GOLD: '#FFD700',
  STROKE_BROWN: '#8B4513',

  // Stroke thicknesses
  STROKE_THIN: 2,
  STROKE_MEDIUM: 3,
  STROKE_THICK: 4,
  STROKE_EXTRA_THICK: 6,

  // Alignments
  ALIGN_LEFT: 'left',
  ALIGN_CENTER: 'center',
  ALIGN_RIGHT: 'right',

  // Font styles
  FONT_STYLE_NORMAL: 'normal',
  FONT_STYLE_ITALIC: 'italic',
  FONT_STYLE_BOLD: 'bold',

  // Origins
  ORIGIN_CENTER: 0.5,
  ORIGIN_TOP_LEFT: 0,
  ORIGIN_TOP_RIGHT: 1,
  ORIGIN_BOTTOM_LEFT: 0,
  ORIGIN_BOTTOM_RIGHT: 1,

  // Depths
  DEPTH_BACKGROUND: -200,
  DEPTH_BACKGROUND_WALLS: -150,
  DEPTH_BACKGROUND_IMAGE: -100,
  DEPTH_BACKGROUND_OVERLAY: -50,
  DEPTH_GRID: 50,
  DEPTH_ITEMS: 100,
  DEPTH_WATCHING_CAT: 85,
  DEPTH_DRAG_RING: 999,
  DEPTH_DUST: 9999,
  DEPTH_JERRY: 10000,
  DEPTH_UI: 2000,
  DEPTH_UI_TEXT: 2100,
  DEPTH_OVERLAY: 9999,
  DEPTH_NOTIFICATION: 10000,
  DEPTH_NOTIFICATION_TEXT: 10001,

  // Sound keys
  SOUND_ITEM_PICKUP: 'item_pickup',
  SOUND_ITEM_DROP: 'item_drop',
  SOUND_MATCH_ELIMINATE: 'match_eliminate',
  SOUND_COMBO_X2: 'combo_x2',
  SOUND_COMBO_X3: 'combo_x3',
  SOUND_COMBO_MEGA: 'combo_mega',
  SOUND_SCORE_GAIN: 'score_gain',
  SOUND_LEVEL_COMPLETE: 'level_complete',
  SOUND_GAME_OVER: 'game_over',
  SOUND_UI_CLICK: 'ui_click',
  SOUND_WHOOSH_FAST: 'whoosh_fast',
  SOUND_TOM_RUNNING_FOOTSTEPS: 'tom_running_footsteps',
  SOUND_TOM_EVIL_LAUGH: 'tom_evil_laugh',
  SOUND_TOM_CRASH_FALL: 'tom_crash_fall',
  SOUND_SCREEN_SHAKE_RUMBLE: 'screen_shake_rumble',

  // Scene keys
  SCENE_LOADING: 'LoadingScene',
  SCENE_TITLE: 'TitleScene',
  SCENE_MODE_SELECTION: 'ModeSelectionScene',
  SCENE_GAME_MODE_MENU: 'GameModeMenuScene',
  SCENE_GAME: 'GameScene',
  SCENE_ONLINE_LOBBY: 'OnlineLobbyScene',
  SCENE_VICTORY: 'VictoryScene',
  SCENE_GAME_OVER: 'GameOverScene',
  SCENE_PAUSE: 'PauseScene',

  // Game modes
  GAME_MODE_SINGLE: 'single',
  GAME_MODE_ONLINE: 'online',
  GAME_MODE_CLASSIC: 'classic',
  GAME_MODE_TIME_ATTACK: 'time_attack',
  GAME_MODE_ENDLESS: 'endless',
  GAME_MODE_ZEN: 'zen',

  // Item types
  ITEM_TYPE_MILK_BOX: 'milk_box',
  ITEM_TYPE_CHIPS_BAG: 'chips_bag',
  ITEM_TYPE_COLA_BOTTLE: 'cola_bottle',
  ITEM_TYPE_COOKIE_BOX: 'cookie_box',
  ITEM_TYPE_DETERGENT_BOTTLE: 'detergent_bottle',
  ITEM_TYPE_TISSUE_PACK: 'tissue_pack',
  ITEM_TYPE_TOOTHPASTE: 'toothpaste',
  ITEM_TYPE_BREAD: 'bread',
  ITEM_TYPE_TOWEL: 'towel',
  ITEM_TYPE_YOGURT_CUPS: 'yogurt_cups',
  ITEM_TYPE_ENERGY_DRINKS: 'energy_drinks',
  ITEM_TYPE_COFFEE_CANS: 'coffee_cans',
  ITEM_TYPE_SOAP_DISPENSERS: 'soap_dispensers',
  ITEM_TYPE_INSTANT_NOODLES: 'instant_noodles',
  ITEM_TYPE_SHAMPOO_BOTTLES: 'shampoo_bottles',
  ITEM_TYPE_JUICE_BOTTLES: 'juice_bottles',
  ITEM_TYPE_CANDY_JARS: 'candy_jars',
  ITEM_TYPE_ANVIL_OBSTACLE: 'anvil_obstacle',
  ITEM_TYPE_SAFE_OBSTACLE: 'safe_obstacle',
  ITEM_TYPE_PIANO_OBSTACLE: 'piano_obstacle',

  // Background keys
  BG_TITLE: 'title_background',
  BG_KITCHEN: 'tom_jerry_kitchen_background',
  BG_LIVING_ROOM: 'tom_jerry_living_room_background',
  BG_GARDEN: 'tom_jerry_garden_background',
  BG_BASEMENT: 'tom_jerry_basement_background',

  // Sprite keys
  SPRITE_JERRY_HEAD: 'jerry_head',
  SPRITE_MOUSE_RUN_AWAY: 'mouse_run_away',
  SPRITE_DUST_CLOUD: 'dust_cloud',
  SPRITE_TOM_CAT_WATCHING: 'tom_cat_watching',
  SPRITE_TOM_CHASING_JERRY: 'tom_chasing_jerry',
  SPRITE_TOM_CARRYING_SACK: 'tom_carrying_sack',
  SPRITE_TOM_TRIPPING: 'tom_tripping',
  SPRITE_TOM_WITH_HAMMER: 'tom_with_hammer',
  SPRITE_CARTOON_BUTTON: 'cartoon_button',
  SPRITE_GAME_TITLE: 'game_title',

  // UI element keys
  UI_OPPONENT_TARGET_1_ICON: 'opponentTarget1Icon',
  UI_OPPONENT_TARGET_1_TEXT: 'opponentTarget1Text',
  UI_OPPONENT_TARGET_2_ICON: 'opponentTarget2Icon',
  UI_OPPONENT_TARGET_2_TEXT: 'opponentTarget2Text',
  UI_OPPONENT_TARGET_3_ICON: 'opponentTarget3Icon',
  UI_OPPONENT_TARGET_3_TEXT: 'opponentTarget3Text',
  UI_OPPONENT_TITLE: 'opponentTitle',
  UI_OPPONENT_BG: 'opponentBg',
  UI_TARGET_BG: 'targetBg',
  UI_TARGET_TEXT: 'targetText',
  UI_MOVE_COUNTER_BG: 'moveCounterBg',
  UI_MOVE_COUNTER_TEXT: 'moveCounterText',
  UI_SCORE_BG: 'scoreBg',
  UI_SCORE_TEXT: 'scoreText',
  UI_PAUSE_BUTTON_BG: 'pauseButtonBg',
  UI_PAUSE_BUTTON_TEXT: 'pauseButtonText',
  UI_SCENE_LABEL: 'sceneLabel',

  // Loading UI keys
  LOADING_TITLE: 'loadingTitle',
  LOADING_PROGRESS_BG: 'progressBg',
  LOADING_PROGRESS_BAR: 'progressBar',
  LOADING_PROGRESS_TEXT: 'progressText',
  LOADING_JERRY_ICON: 'jerryIcon',
  LOADING_TIP_TEXT: 'tipText',

  // Animation keys
  ANIM_JERRY_RUNNING: 'jerry_running',
  ANIM_TOM_CHASING: 'tom_chasing',
  ANIM_TOM_CARRYING: 'tom_carrying',
  ANIM_TOM_TRIPPING: 'tom_tripping',
  ANIM_TOM_HAMMER: 'tom_hammer',

  // Event types
  EVENT_GAME_START: 'gameStart',
  EVENT_GAME_END: 'gameEnd',
  EVENT_LEVEL_COMPLETE: 'levelComplete',
  EVENT_GAME_OVER: 'gameOver',
  EVENT_TIME_UP: 'timeUp',
  EVENT_OPPONENT_LEFT: 'opponentLeft',
  EVENT_MATCH_FOUND: 'matchFound',
  EVENT_COMBO_TRIGGERED: 'comboTriggered',
  EVENT_OBSTACLE_SPAWNED: 'obstacleSpawned',
  EVENT_OBSTACLE_UNLOCKED: 'obstacleUnlocked',
  EVENT_SHUFFLE_TRIGGERED: 'shuffleTriggered',
  EVENT_HELP_TRIGGERED: 'helpTriggered',

  // Multiplayer actions
  MP_ACTION_BACKGROUND_SYNC: 'backgroundSync',
  MP_ACTION_GAME_END: 'gameEnd',

  // Local storage keys
  STORAGE_CURRENT_ROOM_TARGETS: 'currentRoomTargets',
  STORAGE_CURRENT_ROOM_BACKGROUND: 'currentRoomBackground',
  STORAGE_GAME_SETTINGS: 'gameSettings',

  // Default values
  DEFAULT_GRID_ROWS: 3,
  DEFAULT_GRID_COLS: 4,
  DEFAULT_MAX_MOVES: 50,
  DEFAULT_TIME_ATTACK_TIME: 120,
  DEFAULT_MUSIC_VOLUME: 0.3,
  DEFAULT_SFX_VOLUME: 0.5,
  DEFAULT_DEBUG_MODE: false,

  // Debug settings
  DEBUG_GRID_OUTLINES: false,
  DEBUG_ITEM_POSITIONS: false,
  DEBUG_PERFORMANCE_LOGGING: false,
  DEBUG_COLLISION_BOXES: false,

  // Performance settings
  MAX_TWEENS_PER_FRAME: 50,
  TWEEN_POOL_SIZE: 100,
  PARTICLE_POOL_SIZE: 200,
  TEXTURE_POOL_SIZE: 50,

  // Mobile settings
  MOBILE_SCALE_FACTOR: 1.2,
  MOBILE_FONT_MULTIPLIER: 1.2,
  MOBILE_TOUCH_THRESHOLD: 10,
  MOBILE_DRAG_THRESHOLD: 5,

  // Accessibility settings
  ACCESSIBILITY_HIGH_CONTRAST: false,
  ACCESSIBILITY_LARGE_TEXT: false,
  ACCESSIBILITY_REDUCED_MOTION: false,
  ACCESSIBILITY_SCREEN_READER: false,

  // Network settings
  NETWORK_TIMEOUT: 5000,
  NETWORK_RETRY_ATTEMPTS: 3,
  NETWORK_RETRY_DELAY: 1000,

  // Cache settings
  CACHE_TEXTURES: true,
  CACHE_AUDIO: true,
  CACHE_MAX_SIZE: 100 * 1024 * 1024, // 100MB

  // Error messages
  ERROR_TEXTURE_NOT_FOUND: 'Texture not found',
  ERROR_AUDIO_NOT_FOUND: 'Audio not found',
  ERROR_NETWORK_ERROR: 'Network error',
  ERROR_INVALID_GAME_STATE: 'Invalid game state',

  // Success messages
  SUCCESS_GAME_LOADED: 'Game loaded successfully',
  SUCCESS_LEVEL_COMPLETE: 'Level completed!',
  SUCCESS_CONNECTION_ESTABLISHED: 'Connection established',

  // Info messages
  INFO_LOADING_ASSETS: 'Loading assets...',
  INFO_CONNECTING: 'Connecting to server...',
  INFO_WAITING_FOR_OPPONENT: 'Waiting for opponent...',

  // Warning messages
  WARNING_LOW_MEMORY: 'Low memory warning',
  WARNING_SLOW_CONNECTION: 'Slow connection detected',
  WARNING_GAME_OUTDATED: 'Game version outdated',

  // Version info
  VERSION: '1.0.0',
  BUILD_DATE: '2025-01-01',
  BUILD_NUMBER: '001'
}

// Export individual constants for easier importing
export const {
  GRID_ROWS,
  GRID_COLS,
  ITEM_SCALE_NORMAL,
  ITEM_SCALE_DRAG,
  ANIMATION_POP_IN,
  ANIMATION_ELIMINATION,
  DEPTH_BACKGROUND,
  DEPTH_ITEMS,
  DEPTH_UI,
  POSITION_OFFSETS,
  EASE_BACK_OUT,
  VOLUME_SFX_NORMAL,
  COMBO_BASE_POINTS,
  TIMER_WARNING_10SEC,
  TIMER_WARNING_30SEC,
  FONT_SIZE_TITLE,
  FONT_FAMILY_GAME,
  COLOR_WHITE,
  SOUND_ITEM_PICKUP,
  SCENE_LOADING,
  GAME_MODE_SINGLE,
  ITEM_TYPE_MILK_BOX
} = GAME_CONSTANTS